### ISSUE TITLE
[BUG] Section area not displayed

### ISSUE THREAD

**Issue by momo-fr** [wpcleveldotcom/elemental-menu#7]
**Describe the bug**
With the last version (2.0.8) when I enable the mega menu function in the editor no section area are displayed.

**To Reproduce**
1. Go to 'Elementor editor'
2. Click on 'Edit Item for a menu element'
3. Click on 'Submenu -> Enable Mega'
4. No section area are displayed to drop section/widget

**Expected behavior**
With version 2.0.7 and in Container mode it works but with version 2.0.8 it no longer works.

**Screenshots**
![bug_enable_mega_menu](https://user-images.githubusercontent.com/29410831/164039771-d103d1ec-e8fb-4317-83cc-48f8ac2afe3a.jpg)

**Desktop (please complete the following information):**
 - OS: [Mac OS Monterey]
 - Browser [Firefox]
 - Version [99.0.1]

**Additional context**
No problem with 2.0.8 and Container Experience disabled.

**Comment by wpclevel** [comment]
@momo-fr Hi, sorry for the late response! We missed the notification about your issue.
However, we did check carefully and it worked fine on our end: https://www.dropbox.com/s/uqauolvsx6b1epr/elemental-menu-enable-mega-bug.mov?dl=0

If the issue still happens, please send an email to contact@wpclevel.com with a temporary admin account of your site. We will debug and fix the issue if needed.
